apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - image: swr.cn-east-3.myhuaweicloud.com/batch/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        command:
          - sleep
        args:
          - '1000'
        name: jenkins-test
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
